name: hello-world
on: push
jobs:
  my-job:
    runs-on: container: gradle:6-jdk11
    name: My Job
    steps:
    - name: Clone-down
      uses: actions/checkout@v3   
    - name: my-step
      run: ci/build-app.sh
