name: Java CI
on: push
jobs:
  Clone-down:
    name: Clone repo
    runs-on: ubuntu-latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v3 
      - name: Upload Repo
      uses: actions/upload-artifact@v3
      with: 
        name: code
        path: . 
  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11 
    name: My Job
    steps: 
    - name: Build-app
      run: ci/build-app.sh
    - name: Test
      run: ci/unit-test-app.sh
    - name: Download Repo
      uses: actions/download-artifact@v3
      with: 
        name: code
        path: .
